#!/bin/bash

OUTPUT=""
COUNT=0

for pid in $(pidof tinydb); do
   children="$(pgrep -P $pid)"
   if [ -n "$children" ]; then
      OUTPUT+=$'\n\t'
      OUTPUT+="Sync process $pid"
      kill -s SIGUSR1 $pid
      COUNT=$(( COUNT + 1 ))
   fi
done

if [[ $COUNT -eq 0 ]]; then
   echo "Aucune instance de tinydb n'est en cours."
else
   echo -n "$COUNT instances en cours :"
   echo "$OUTPUT"
   echo "Done"
fi
